#pragma once
#include "PlanszaBuilder.hpp"

class Konwerter {
private:
	Plansza * plansza;
	PlanszaBuilder * budowniczy;
	string schematS = "MMMMMMMM-MMZGWMM-MMKDKZMM-MDZGZDM-MMGWWGMM-MMDPWMM-MMMMMMMM";
	string schematD = "NNNNNNNNNNNNNNNN-NNNNNNNNN-NNNNNDDDDDDNNNNN-NNDDDDNN-NNNNDDDDDDDDNNNN-NNDDDDDNN-NNNDDDDDDDDDDNNN-NDDDDDDN-NNNDDDDDDDDDDNNN-NNDDDDDNN-NNNNDDDDDDDDNNNN-NNDDDDNN-NNNNNDDDDDDNNNNN-NNNNNNNNN-NNNNNNNNNNNNNNNN";
	string schematO = "NNNNNNNNNNNNNNNNN-NNNNNOOOOOOONNNNN-NNNNOOOOOOOOONNNN-NNNOOOOOOOOOOONNN-NNNOOOOOOOOOOONNN-NNNNOOOOOOOOONNNN-NNNNNOOOOOOONNNNN-NNNNNNNNNNNNNNNNN";
	string schematP = "NNNNNNNNNNNNNNNN-NNNNNNNNN-NNNNNNNPNNKNNNNN-NNNNNNNN-NNNNDNNNNNNNNNNN - NNNNNNNNN - NNNNNNNNNNNNPNNN - NPNNNNNN - NNNNNNNNNNNNNNNN - NNNNNNWNN - NNNNZNNNNNNNNNNN - NNNNNNNN - NNNNNNPNNNGNNNNN - NNNNNNNNN - NNNNNNNNNNNNNNNN";
public:
	void przypiszBudowniczego(PlanszaBuilder & budowniczy);
	void przypiszBudowniczego(PlanszaBuilder * budowniczy);
	void wczytajSchematS(string & schemat);
	void wczytajSchematS(string * schemat);
	void przetworzSchemat();
	Plansza * zwrocPlansze();
};